const PRODUCTS = [
  {
    id: 1,
    slug: "iphone-16-128gb",
    name: "Apple iPhone 16 128GB",
    category: "phones",
    categoryLabel: "Điện thoại",
    brand: "Apple",
    price: 19990000,
    oldPrice: 22990000,
    rating: 4.9,
    stock: 18,
    featured: true,
    image: "assets/images/products/iphone-16.webp",
    badge: "Bán chạy",
    short: "Chip A18, màn hình OLED 6.1 inch, camera Fusion 48MP.",
    description:
      "iPhone 16 sở hữu chip A18, màn hình Super Retina XDR OLED 6.1 inch, Camera Control và cụm camera Fusion 48MP hỗ trợ chụp ảnh linh hoạt.",
    specs: {
      "Màn hình": "6.1 inch Super Retina XDR OLED",
      Chip: "Apple A18",
      RAM: "Không công bố",
      "Bộ nhớ": "128GB",
      "Camera sau": "48MP Fusion + 12MP Ultra Wide",
      "Camera trước": "12MP",
      "Kết nối": "5G, Wi‑Fi 7, Bluetooth 5.3",
      "Kháng nước": "IP68",
    },
    source: "https://www.apple.com/vn/iphone-16/specs/",
  },
  {
    id: 2,
    slug: "samsung-galaxy-s25-256gb",
    name: "Samsung Galaxy S25 256GB",
    category: "phones",
    categoryLabel: "Điện thoại",
    brand: "Samsung",
    price: 20990000,
    oldPrice: 22990000,
    rating: 4.8,
    stock: 13,
    featured: true,
    image: "assets/images/products/galaxy-s25.webp",
    badge: "AI Phone",
    short: "Snapdragon 8 Elite, AMOLED 120Hz, RAM 12GB.",
    description:
      "Galaxy S25 là mẫu flagship nhỏ gọn với màn hình Dynamic AMOLED 2X 120Hz, Snapdragon 8 Elite for Galaxy, RAM 12GB và bộ tính năng Galaxy AI.",
    specs: {
      "Màn hình": "6.2 inch Dynamic AMOLED 2X, 120Hz",
      Chip: "Snapdragon 8 Elite for Galaxy",
      RAM: "12GB",
      "Bộ nhớ": "256GB",
      "Camera sau": "50MP + 12MP + 10MP",
      "Camera trước": "12MP",
      Pin: "4.000mAh, sạc 25W",
      "Kháng nước": "IP68",
    },
    source: "https://www.samsung.com/vn/smartphones/galaxy-s25/specs/",
  },
  {
    id: 3,
    slug: "xiaomi-15-512gb",
    name: "Xiaomi 15 12GB/512GB",
    category: "phones",
    categoryLabel: "Điện thoại",
    brand: "Xiaomi",
    price: 24990000,
    oldPrice: 26990000,
    rating: 4.8,
    stock: 9,
    featured: true,
    image: "assets/images/products/xiaomi-15.webp",
    badge: "Camera Leica",
    short: "Snapdragon 8 Elite, màn hình 6.36 inch, camera Leica.",
    description:
      "Xiaomi 15 kết hợp màn hình AMOLED 6.36 inch nhỏ gọn, Snapdragon 8 Elite, bộ nhớ UFS 4.0 và hệ thống ba camera 50MP đồng phát triển với Leica.",
    specs: {
      "Màn hình": "6.36 inch AMOLED, 120Hz",
      Chip: "Snapdragon 8 Elite",
      RAM: "12GB LPDDR5X",
      "Bộ nhớ": "512GB UFS 4.0",
      "Camera sau": "50MP + 50MP + 50MP Leica",
      "Camera trước": "32MP",
      Pin: "5.240mAh, sạc 90W",
      "Kháng nước": "IP68",
    },
    source: "https://www.mi.com/vn/product/xiaomi-15/specs/",
  },
  {
    id: 4,
    slug: "oppo-reno13-5g-256gb",
    name: "OPPO Reno13 5G 12GB/256GB",
    category: "phones",
    categoryLabel: "Điện thoại",
    brand: "OPPO",
    price: 15990000,
    oldPrice: 16990000,
    rating: 4.7,
    stock: 16,
    featured: false,
    image: "assets/images/products/oppo-reno13.webp",
    badge: "Chụp ảnh đẹp",
    short: "AMOLED 120Hz, Dimensity 8350, pin 5.600mAh.",
    description:
      "OPPO Reno13 5G có thiết kế mỏng nhẹ, màn hình AMOLED 120Hz, chip Dimensity 8350, camera chính 50MP có OIS và pin lớn hỗ trợ sạc nhanh.",
    specs: {
      "Màn hình": "6.59 inch AMOLED, 120Hz",
      Chip: "MediaTek Dimensity 8350",
      RAM: "12GB LPDDR5X",
      "Bộ nhớ": "256GB UFS 3.1",
      "Camera sau": "50MP OIS + 8MP + 2MP",
      "Camera trước": "50MP",
      Pin: "5.600mAh, sạc 80W",
      "Kháng nước": "IP69/IP68/IP66",
    },
    source: "https://www.oppo.com/vn/smartphones/series-reno/reno13/specs/",
  },
  {
    id: 5,
    slug: "lenovo-loq-15irx9",
    name: "Lenovo LOQ 15IRX9",
    category: "laptops",
    categoryLabel: "Laptop",
    brand: "Lenovo",
    price: 24990000,
    oldPrice: 27990000,
    rating: 4.8,
    stock: 8,
    featured: true,
    image: "assets/images/products/lenovo-loq-15irx9.webp",
    badge: "Gaming",
    short: "Core i5-13450HX, RTX 4050, màn hình 144Hz.",
    description:
      "Lenovo LOQ 15IRX9 hướng đến học tập, lập trình và chơi game với CPU Intel Core HX, GPU RTX 40 series, màn hình 15.6 inch 144Hz và khả năng nâng cấp tốt.",
    specs: {
      CPU: "Intel Core i5-13450HX",
      GPU: "NVIDIA GeForce RTX 4050 6GB",
      RAM: "16GB DDR5",
      SSD: "512GB PCIe 4.0",
      "Màn hình": "15.6 inch FHD IPS 144Hz",
      Pin: "60Wh",
      "Khối lượng": "Khoảng 2.38kg",
      "Hệ điều hành": "Windows 11",
    },
    source:
      "https://www.lenovo.com/vn/vi/p/laptops/loq-laptops/lenovo-loq-15irx9/len101q0005",
  },
  {
    id: 6,
    slug: "asus-vivobook-15-x1504",
    name: "ASUS Vivobook 15 X1504",
    category: "laptops",
    categoryLabel: "Laptop",
    brand: "ASUS",
    price: 14490000,
    oldPrice: 15990000,
    rating: 4.6,
    stock: 15,
    featured: false,
    image: "assets/images/products/asus-vivobook-15.webp",
    badge: "Sinh viên",
    short: "Core i5 thế hệ 13, màn hình FHD 15.6 inch, SSD 512GB.",
    description:
      "ASUS Vivobook 15 X1504 phù hợp học tập và văn phòng với thiết kế gọn, màn hình FHD 15.6 inch, bàn phím số và ổ SSD tốc độ cao.",
    specs: {
      CPU: "Intel Core i5-1335U",
      GPU: "Intel Iris Xe",
      RAM: "16GB DDR4",
      SSD: "512GB NVMe",
      "Màn hình": "15.6 inch FHD 60Hz",
      "Kết nối": "USB-C, USB-A, HDMI",
      "Khối lượng": "Khoảng 1.70kg",
      "Hệ điều hành": "Windows 11",
    },
    source:
      "https://www.asus.com/vn/laptops/for-home/vivobook/asus-vivobook-15-x1504/techspec/",
  },
  {
    id: 7,
    slug: "macbook-air-13-m4",
    name: "MacBook Air 13 inch M4",
    category: "laptops",
    categoryLabel: "Laptop",
    brand: "Apple",
    price: 26990000,
    oldPrice: 28990000,
    rating: 4.9,
    stock: 11,
    featured: true,
    image: "assets/images/products/macbook-air-m4.webp",
    badge: "Mỏng nhẹ",
    short: "Chip Apple M4, RAM 16GB, màn hình Liquid Retina 13.6 inch.",
    description:
      "MacBook Air M4 có thiết kế mỏng nhẹ, hoạt động êm không quạt, màn hình Liquid Retina sắc nét và thời lượng pin dài cho học tập, lập trình và sáng tạo.",
    specs: {
      "CPU/GPU": "Apple M4",
      RAM: "16GB unified memory",
      SSD: "256GB",
      "Màn hình": "13.6 inch Liquid Retina",
      Camera: "12MP Center Stage",
      Cổng: "MagSafe 3, 2 x Thunderbolt 4",
      "Khối lượng": "Khoảng 1.24kg",
      "Hệ điều hành": "macOS",
    },
    source: "https://www.apple.com/vn/macbook-air/specs/",
  },
  {
    id: 8,
    slug: "acer-nitro-v-15",
    name: "Acer Nitro V 15 ANV15-51",
    category: "laptops",
    categoryLabel: "Laptop",
    brand: "Acer",
    price: 22990000,
    oldPrice: 24990000,
    rating: 4.7,
    stock: 7,
    featured: false,
    image: "assets/images/products/acer-nitro-v15.webp",
    badge: "Hiệu năng",
    short: "Core i5 H-series, RTX 4050, màn hình 144Hz.",
    description:
      "Acer Nitro V 15 là laptop gaming tầm trung có màn hình 144Hz, GPU RTX 4050 và hệ thống tản nhiệt hai quạt, phù hợp học CNTT lẫn giải trí.",
    specs: {
      CPU: "Intel Core i5-13420H",
      GPU: "NVIDIA GeForce RTX 4050 6GB",
      RAM: "16GB DDR5",
      SSD: "512GB NVMe",
      "Màn hình": "15.6 inch FHD IPS 144Hz",
      "Kết nối": "Wi‑Fi 6, HDMI 2.1, USB-C",
      "Khối lượng": "Khoảng 2.11kg",
      "Hệ điều hành": "Windows 11",
    },
    source: "https://www.acer.com/vn-vi/laptops/nitro/nitro-v-15",
  },
  {
    id: 9,
    slug: "ipad-air-11-m4",
    name: "iPad Air 11 inch M4",
    category: "tablets",
    categoryLabel: "Máy tính bảng",
    brand: "Apple",
    price: 16990000,
    oldPrice: 17990000,
    rating: 4.9,
    stock: 14,
    featured: true,
    image: "assets/images/products/ipad-air-m4.webp",
    badge: "Mới",
    short: "Chip M4, màn hình Liquid Retina 11 inch, hỗ trợ Apple Pencil Pro.",
    description:
      "iPad Air 11 inch M4 có hiệu năng mạnh, màn hình Liquid Retina chuẩn màu, camera ngang Center Stage và hỗ trợ Apple Pencil Pro cùng Magic Keyboard.",
    specs: {
      "Màn hình": "11 inch Liquid Retina",
      Chip: "Apple M4",
      "Bộ nhớ": "128GB",
      "Camera sau": "12MP Wide",
      "Camera trước": "12MP Center Stage",
      "Kết nối": "Wi‑Fi 6E, USB‑C",
      "Phụ kiện": "Apple Pencil Pro, Magic Keyboard",
      "Hệ điều hành": "iPadOS",
    },
    source: "https://www.apple.com/vn/ipad-air/specs/",
  },
  {
    id: 10,
    slug: "galaxy-tab-s10-fe",
    name: "Samsung Galaxy Tab S10 FE",
    category: "tablets",
    categoryLabel: "Máy tính bảng",
    brand: "Samsung",
    price: 13990000,
    oldPrice: 15490000,
    rating: 4.7,
    stock: 12,
    featured: true,
    image: "assets/images/products/galaxy-tab-s10-fe.webp",
    badge: "Kèm S Pen",
    short: "Màn hình 10.9 inch 90Hz, Exynos 1580, kháng nước IP68.",
    description:
      "Galaxy Tab S10 FE phù hợp ghi chú và học tập nhờ màn hình lớn, bút S Pen đi kèm, khả năng đa nhiệm và chuẩn kháng nước bụi IP68.",
    specs: {
      "Màn hình": "10.9 inch, 90Hz",
      Chip: "Exynos 1580",
      RAM: "8GB",
      "Bộ nhớ": "128GB, hỗ trợ microSD",
      "Camera sau": "13MP",
      "Camera trước": "12MP Ultra Wide",
      Pin: "8.000mAh, sạc 45W",
      "Kháng nước": "IP68",
    },
    source:
      "https://www.samsung.com/vn/tablets/galaxy-tab-s/galaxy-tab-s10-fe/",
  },
  {
    id: 11,
    slug: "xiaomi-pad-7",
    name: "Xiaomi Pad 7 8GB/256GB",
    category: "tablets",
    categoryLabel: "Máy tính bảng",
    brand: "Xiaomi",
    price: 8990000,
    oldPrice: 9990000,
    rating: 4.7,
    stock: 20,
    featured: false,
    image: "assets/images/products/xiaomi-pad-7.webp",
    badge: "Giá tốt",
    short: "Màn hình 3.2K 144Hz, Snapdragon 7+ Gen 3, pin 8.850mAh.",
    description:
      "Xiaomi Pad 7 có màn hình độ phân giải cao 3.2K, tần số quét 144Hz, cấu hình mạnh và hệ thống bốn loa phù hợp học tập lẫn giải trí.",
    specs: {
      "Màn hình": "11.2 inch 3.2K, 144Hz",
      Chip: "Snapdragon 7+ Gen 3",
      RAM: "8GB",
      "Bộ nhớ": "256GB",
      "Camera sau": "13MP",
      "Camera trước": "8MP",
      Pin: "8.850mAh, sạc 45W",
      "Âm thanh": "4 loa Dolby Atmos",
    },
    source: "https://www.mi.com/global/product/xiaomi-pad-7/specs/",
  },
  {
    id: 12,
    slug: "lenovo-yoga-tab-plus",
    name: "Lenovo Yoga Tab Plus",
    category: "tablets",
    categoryLabel: "Máy tính bảng",
    brand: "Lenovo",
    price: 18990000,
    oldPrice: 20990000,
    rating: 4.8,
    stock: 6,
    featured: false,
    image: "assets/images/products/lenovo-yoga-tab-plus.webp",
    badge: "AI Tablet",
    short: "Màn hình 12.7 inch 3K, Snapdragon 8 Gen 3, âm thanh Harman Kardon.",
    description:
      "Lenovo Yoga Tab Plus là tablet màn hình lớn hướng đến làm việc và giải trí, dùng Snapdragon 8 Gen 3, màn hình 3K và hệ thống loa Harman Kardon.",
    specs: {
      "Màn hình": "12.7 inch 3K, 144Hz",
      Chip: "Snapdragon 8 Gen 3",
      RAM: "16GB",
      "Bộ nhớ": "256GB",
      Camera: "13MP sau, 13MP trước",
      Pin: "10.200mAh",
      "Âm thanh": "6 loa Harman Kardon",
      "Hệ điều hành": "Android",
    },
    source:
      "https://www.lenovo.com/vn/vi/p/tablets/lenovo-yoga-tab-plus/len103y0001",
  },
  {
    id: 13,
    slug: "airpods-4-anc",
    name: "Apple AirPods 4 ANC",
    category: "headphones",
    categoryLabel: "Tai nghe",
    brand: "Apple",
    price: 4790000,
    oldPrice: 4990000,
    rating: 4.8,
    stock: 25,
    featured: true,
    image: "assets/images/products/airpods-4-anc.webp",
    badge: "Chống ồn",
    short: "Chip H2, chống ồn chủ động, âm thanh không gian.",
    description:
      "AirPods 4 phiên bản chống ồn sử dụng chip H2, hỗ trợ Adaptive Audio, Transparency, Personalized Spatial Audio và hộp sạc USB‑C.",
    specs: {
      "Kiểu tai nghe": "True wireless earbuds",
      Chip: "Apple H2",
      "Chống ồn": "ANC + Transparency",
      Microphone: "Beamforming microphones",
      "Kết nối": "Bluetooth 5.3",
      "Hộp sạc": "USB‑C, hỗ trợ sạc không dây",
      "Kháng nước": "IP54",
      "Tương thích": "iOS, iPadOS, macOS",
    },
    source: "https://www.apple.com/vn/airpods-4/specs/",
  },
  {
    id: 14,
    slug: "galaxy-buds3-pro",
    name: "Samsung Galaxy Buds3 Pro",
    category: "headphones",
    categoryLabel: "Tai nghe",
    brand: "Samsung",
    price: 4490000,
    oldPrice: 4990000,
    rating: 4.7,
    stock: 19,
    featured: true,
    image: "assets/images/products/galaxy-buds3-pro.webp",
    badge: "Hi‑Fi",
    short: "Loa 2 đường tiếng, ANC thông minh, âm thanh 24-bit.",
    description:
      "Galaxy Buds3 Pro có thiết kế thân tai nghe mới, hệ thống loa hai đường tiếng, chống ồn chủ động thích ứng và hỗ trợ âm thanh chất lượng cao trên thiết bị Galaxy.",
    specs: {
      "Kiểu tai nghe": "True wireless in-ear",
      Driver: "2-way speaker",
      "Chống ồn": "Adaptive ANC",
      "Âm thanh": "24-bit / 96kHz trên thiết bị hỗ trợ",
      "Kết nối": "Bluetooth 5.4",
      "Thời lượng": "Tối đa khoảng 30 giờ với hộp",
      "Kháng nước": "IP57",
      "Tương thích": "Android, iOS giới hạn",
    },
    source:
      "https://www.samsung.com/vn/audio-sound/galaxy-buds/galaxy-buds3-pro/",
  },
  {
    id: 15,
    slug: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    category: "headphones",
    categoryLabel: "Tai nghe",
    brand: "Sony",
    price: 7490000,
    oldPrice: 8490000,
    rating: 4.9,
    stock: 10,
    featured: true,
    image: "assets/images/products/sony-wh1000xm5.webp",
    badge: "Cao cấp",
    short: "Tai nghe chụp tai chống ồn, hỗ trợ LDAC, pin 30 giờ.",
    description:
      "Sony WH-1000XM5 là tai nghe over-ear cao cấp với hệ thống chống ồn đa micro, âm thanh LDAC, đàm thoại rõ và pin dài.",
    specs: {
      "Kiểu tai nghe": "Over-ear không dây",
      Driver: "30mm",
      "Chống ồn": "ANC đa microphone",
      Codec: "SBC, AAC, LDAC",
      "Kết nối": "Bluetooth 5.2, 3.5mm",
      "Thời lượng": "Tối đa 30 giờ khi bật ANC",
      "Sạc nhanh": "3 phút nghe khoảng 3 giờ",
      "Khối lượng": "Khoảng 250g",
    },
    source:
      "https://www.sony.com.vn/electronics/tai-nghe-choang-dau/wh-1000xm5/specifications",
  },
  {
    id: 16,
    slug: "jbl-tune-770nc",
    name: "JBL Tune 770NC",
    category: "headphones",
    categoryLabel: "Tai nghe",
    brand: "JBL",
    price: 2490000,
    oldPrice: 2990000,
    rating: 4.6,
    stock: 22,
    featured: false,
    image: "assets/images/products/jbl-tune-770nc.webp",
    badge: "Pin lâu",
    short: "Chống ồn thích ứng, JBL Pure Bass, pin tối đa 70 giờ.",
    description:
      "JBL Tune 770NC có thiết kế gập gọn, chống ồn thích ứng, kết nối đa điểm và thời lượng pin dài cho nhu cầu học tập, di chuyển.",
    specs: {
      "Kiểu tai nghe": "Over-ear không dây",
      Driver: "40mm",
      "Chống ồn": "Adaptive Noise Cancelling",
      "Kết nối": "Bluetooth 5.3, cáp 3.5mm",
      "Thời lượng": "Tối đa 70 giờ",
      "Sạc nhanh": "5 phút nghe khoảng 3 giờ",
      "Ứng dụng": "JBL Headphones",
      "Khối lượng": "Khoảng 232g",
    },
    source: "https://www.jbl.com/over-ear-headphones/TUNE770NC.html",
  },
  {
    id: 17,
    slug: "apple-usb-c-20w",
    name: "Apple USB‑C Power Adapter 20W",
    category: "chargers",
    categoryLabel: "Sạc & cáp",
    brand: "Apple",
    price: 549000,
    oldPrice: 590000,
    rating: 4.8,
    stock: 40,
    featured: false,
    image: "assets/images/products/apple-20w.webp",
    badge: "Chính hãng",
    short: "Củ sạc USB‑C 20W hỗ trợ sạc nhanh cho iPhone và iPad.",
    description:
      "Bộ tiếp hợp nguồn USB‑C 20W của Apple hỗ trợ sạc nhanh cho các mẫu iPhone tương thích và dùng được với nhiều thiết bị USB‑C.",
    specs: {
      Cổng: "1 x USB‑C",
      "Công suất": "20W",
      "Chuẩn sạc": "USB Power Delivery",
      "Điện áp vào": "100–240V",
      "Tương thích": "iPhone, iPad và thiết bị USB‑C",
      "Cáp đi kèm": "Không",
      Màu: "Trắng",
      "Bảo hành": "Theo nhà bán lẻ",
    },
    source:
      "https://www.apple.com/vn/shop/product/MW2K3ZA/A/b%E1%BB%99-ti%E1%BA%BFp-h%E1%BB%A3p-ngu%E1%BB%93n-usb-c-20w",
  },
  {
    id: 18,
    slug: "samsung-25w-power-adapter",
    name: "Samsung Power Adapter 25W",
    category: "chargers",
    categoryLabel: "Sạc & cáp",
    brand: "Samsung",
    price: 590000,
    oldPrice: 690000,
    rating: 4.7,
    stock: 35,
    featured: false,
    image: "assets/images/products/samsung-25w.webp",
    badge: "Super Fast Charging",
    short: "Sạc USB‑C 25W hỗ trợ USB PD PPS.",
    description:
      "Củ sạc Samsung 25W hỗ trợ Super Fast Charging thông qua USB Power Delivery PPS, phù hợp nhiều điện thoại và máy tính bảng Galaxy.",
    specs: {
      Cổng: "1 x USB‑C",
      "Công suất": "Tối đa 25W",
      "Chuẩn sạc": "USB PD 3.0 PPS",
      "Điện áp vào": "100–240V",
      "Tương thích": "Thiết bị USB‑C PD/PPS",
      "Cáp đi kèm": "Tùy phiên bản",
      Màu: "Đen hoặc trắng",
      "Bảo vệ": "Quá dòng, quá nhiệt",
    },
    source:
      "https://www.samsung.com/vn/mobile-accessories/25w-power-adapter-black-ep-t2510nbegww/",
  },
  {
    id: 19,
    slug: "anker-nano-30w",
    name: "Anker Nano 3 30W",
    category: "chargers",
    categoryLabel: "Sạc & cáp",
    brand: "Anker",
    price: 520000,
    oldPrice: 650000,
    rating: 4.7,
    stock: 31,
    featured: true,
    image: "assets/images/products/anker-nano-30w.webp",
    badge: "Nhỏ gọn",
    short: "Sạc GaN 30W nhỏ gọn, hỗ trợ Power Delivery.",
    description:
      "Anker Nano 3 sử dụng công nghệ GaN để đạt công suất 30W trong thiết kế nhỏ, phù hợp điện thoại, tablet và một số laptop mỏng nhẹ.",
    specs: {
      Cổng: "1 x USB‑C",
      "Công suất": "30W",
      "Công nghệ": "GaN",
      "Chuẩn sạc": "USB Power Delivery",
      "Điện áp vào": "100–240V",
      "Tương thích": "iPhone, Android, iPad, MacBook Air",
      "Cáp đi kèm": "Không",
      "Kích thước": "Siêu nhỏ gọn",
    },
    source: "https://www.anker.com/products/a2147",
  },
  {
    id: 20,
    slug: "baseus-gan5-pro-65w",
    name: "Baseus GaN5 Pro 65W",
    category: "chargers",
    categoryLabel: "Sạc & cáp",
    brand: "Baseus",
    price: 899000,
    oldPrice: 1090000,
    rating: 4.6,
    stock: 26,
    featured: false,
    image: "assets/images/products/baseus-gan5-pro-65w.webp",
    badge: "3 cổng",
    short: "Sạc GaN 65W, 2 USB‑C và 1 USB‑A.",
    description:
      "Baseus GaN5 Pro 65W cho phép sạc đồng thời nhiều thiết bị với hai cổng USB‑C và một cổng USB‑A, phù hợp điện thoại, tablet và laptop.",
    specs: {
      Cổng: "2 x USB‑C, 1 x USB‑A",
      "Tổng công suất": "65W",
      "Công nghệ": "GaN5",
      "Chuẩn sạc": "PD, PPS, QC",
      "Điện áp vào": "100–240V",
      "Tương thích": "Laptop USB‑C, điện thoại, tablet",
      "Cáp đi kèm": "Tùy bộ sản phẩm",
      "Bảo vệ": "Quá nhiệt, quá áp, quá dòng",
    },
    source: "https://www.baseus.com/products/gan5-pro-fast-charger-2c-u-65w",
  },
  {
    id: 21,
    slug: "jbl-flip-7",
    name: "JBL Flip 7",
    category: "speakers",
    categoryLabel: "Loa",
    brand: "JBL",
    price: 3490000,
    oldPrice: 3990000,
    rating: 4.8,
    stock: 17,
    featured: true,
    image: "assets/images/products/jbl-flip-7.webp",
    badge: "Chống nước",
    short: "Loa Bluetooth di động, AI Sound Boost, IP68.",
    description:
      "JBL Flip 7 là loa di động nhỏ gọn với âm thanh JBL Pro Sound, AI Sound Boost, chuẩn IP68 và khả năng kết nối nhiều loa tương thích.",
    specs: {
      Loại: "Loa Bluetooth di động",
      "Kết nối": "Bluetooth 5.4",
      "Công suất": "Theo nhà sản xuất",
      "Thời lượng": "Tối đa khoảng 16 giờ",
      "Kháng nước/bụi": "IP68",
      "Tính năng": "AI Sound Boost, Auracast",
      Sạc: "USB‑C",
      "Ứng dụng": "JBL Portable",
    },
    source: "https://www.jbl.com/bluetooth-speakers/JBLFLIP7.html",
  },
  {
    id: 22,
    slug: "sony-ult-field-1",
    name: "Sony ULT FIELD 1",
    category: "speakers",
    categoryLabel: "Loa",
    brand: "Sony",
    price: 2990000,
    oldPrice: 3490000,
    rating: 4.7,
    stock: 21,
    featured: false,
    image: "assets/images/products/sony-ult-field-1.webp",
    badge: "Bass mạnh",
    short: "Loa Bluetooth nhỏ gọn, ULT Power Sound, IP67.",
    description:
      "Sony ULT FIELD 1 có chế độ ULT tăng cường âm trầm, thiết kế chống nước bụi IP67, dây đeo linh hoạt và hỗ trợ đàm thoại rảnh tay.",
    specs: {
      Loại: "Loa Bluetooth di động",
      "Kết nối": "Bluetooth",
      "Thời lượng": "Tối đa khoảng 12 giờ",
      "Kháng nước/bụi": "IP67",
      "Tính năng": "ULT Power Sound, speakerphone",
      Sạc: "USB‑C",
      "Vị trí đặt": "Dọc hoặc ngang",
      "Ứng dụng": "Sony Music Center",
    },
    source: "https://www.sony.com.vn/wireless-speakers/products/ult-field-1",
  },
  {
    id: 23,
    slug: "marshall-emberton-iii",
    name: "Marshall Emberton III",
    category: "speakers",
    categoryLabel: "Loa",
    brand: "Marshall",
    price: 4990000,
    oldPrice: 5490000,
    rating: 4.8,
    stock: 12,
    featured: true,
    image: "assets/images/products/marshall-emberton-iii.webp",
    badge: "Thiết kế cổ điển",
    short: "Âm thanh True Stereophonic, pin hơn 32 giờ, IP67.",
    description:
      "Marshall Emberton III giữ phong cách ampli cổ điển, phát âm thanh đa hướng True Stereophonic, pin dài và chuẩn chống nước bụi IP67.",
    specs: {
      Loại: "Loa Bluetooth di động",
      "Kết nối": "Bluetooth 5.3 LE",
      "Thời lượng": "Hơn 32 giờ",
      "Kháng nước/bụi": "IP67",
      "Âm thanh": "True Stereophonic",
      "Sạc nhanh": "20 phút cho khoảng 6 giờ",
      Sạc: "USB‑C",
      "Ứng dụng": "Marshall Bluetooth",
    },
    source: "https://www.marshall.com/vn/en/product/emberton-iii",
  },
  {
    id: 24,
    slug: "bose-soundlink-flex-2",
    name: "Bose SoundLink Flex Gen 2",
    category: "speakers",
    categoryLabel: "Loa",
    brand: "Bose",
    price: 4190000,
    oldPrice: 4690000,
    rating: 4.8,
    stock: 14,
    featured: false,
    image: "assets/images/products/bose-soundlink-flex-2.webp",
    badge: "Âm thanh cân bằng",
    short: "Loa Bluetooth IP67, PositionIQ, pin tối đa 12 giờ.",
    description:
      "Bose SoundLink Flex thế hệ 2 mang lại âm thanh cân bằng, tự điều chỉnh theo hướng đặt nhờ PositionIQ, thiết kế bền và chuẩn IP67.",
    specs: {
      Loại: "Loa Bluetooth di động",
      "Kết nối": "Bluetooth 5.3",
      "Thời lượng": "Tối đa khoảng 12 giờ",
      "Kháng nước/bụi": "IP67",
      "Tính năng": "PositionIQ, multipoint",
      Sạc: "USB‑C",
      Microphone: "Có",
      "Ứng dụng": "Bose app",
    },
    source:
      "https://www.bose.com/p/speakers/bose-soundlink-flex-portable-speaker-2nd-gen/SLFLXII-SPEAKERWIRELESS.html",
  },
];
